In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [4]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
x.shape

(3, 4)

In [6]:
y = np.ones((3,4), dtype=np.int16)
y

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [7]:
x = np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
y = np.ones((3,4), dtype=np.float64)
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full((3,4) ,0.11)

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [10]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [11]:
np.arange(10, 30 ,5)

array([10, 15, 20, 25])

In [12]:
np.arange(0, 2 ,.5)

array([0. , 0.5, 1. , 1.5])

In [13]:
x =[
    [
        [1],
        [1],
        [1],
        [1]
    ],
    [
        [1],
        [1],
        [1],
        [1]
    ]
]

In [14]:
np.array(x).shape

(2, 4, 1)

In [15]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
np.random.rand(2,3)

array([[0.73380657, 0.39725765, 0.44157798],
       [0.60843224, 0.81450554, 0.54591743]])

In [17]:
c = np.arange(1, 5)
c

array([1, 2, 3, 4])

In [18]:
c.dtype

dtype('int64')

In [19]:
c.itemsize

8

In [20]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [21]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
a = np.array([1,5,6,8,3,6,9])
a[1]

5

In [23]:
a[2:5]

array([6, 8, 3])

In [24]:
print(a[2::2])
print(a[2::3])
print(a[::-1])
print(a[::-2])

[6 3 9]
[6 6]
[9 6 3 8 6 5 1]
[9 3 6 1]


In [25]:
a = np.array([1,5,3,19,13,7,3])
a[1:3] = -1
a[3:] = 0
print(a)

[ 1 -1 -1  0  0  0  0]


In [26]:
a = np.array([1,2,5,7,8,9,4])
a_slice = a[1:5]
a_slice[1] = 1000
print(a)

[   1    2 1000    7    8    9    4]


In [27]:
another_slice = a[2:6].copy()
another_slice[1] = 23333
print(another_slice) #modified
print(a) #unchanged

[ 1000 23333     8     9]
[   1    2 1000    7    8    9    4]


In [28]:
x = np.random.rand(4,5)
x

array([[0.97284651, 0.61115013, 0.48341966, 0.12766404, 0.63744144],
       [0.9710674 , 0.96251907, 0.25557692, 0.92485321, 0.85815111],
       [0.67555678, 0.9385    , 0.20923267, 0.86086628, 0.18041998],
       [0.92903021, 0.08497835, 0.06830045, 0.39718342, 0.62713705]])

In [29]:
x[1]

array([0.9710674 , 0.96251907, 0.25557692, 0.92485321, 0.85815111])

In [30]:
print(x[1,1])
print(x[1][1])

0.9625190658566949
0.9625190658566949


In [31]:
x[1:3,3:5]

array([[0.92485321, 0.85815111],
       [0.86086628, 0.18041998]])

In [32]:
x[2:4 , 0:3]

array([[0.67555678, 0.9385    , 0.20923267],
       [0.92903021, 0.08497835, 0.06830045]])

In [33]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
rows_on = np.array([True, False, True])

In [35]:
rows_on

array([ True, False,  True])

In [36]:
a[rows_on]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [37]:
a = np.array([20,30,40,50])
b = np.arange( 4 )
print(a)
print(b)
c = a+b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [38]:
A = np.array([[1,1],
            [0,1]])

B = np.array([[2,0],
            [3,4]])

print(A*B)

[[2 0]
 [0 4]]


In [39]:
print(np.dot(A,B))

[[5 4]
 [3 4]]


In [40]:
list = [1,2,3]

In [41]:
list_array = np.array(list)

In [42]:
list_array

array([1, 2, 3])

In [43]:
tup = (1,2,3)
my_tup_array = np.array(tup)
my_tup_array

array([1, 2, 3])

In [44]:
#Time comparison of a NumPy operation and a corresponding Python code

def multiply_loops(A, B):
    c = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[1]):
        for j in range(B.shape[0]):
            c[i,j] = A[i,j] * B[j,i]
    return c

In [45]:
def multiply_vector(A, B):
     return A @ B

In [46]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

In [47]:
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

4.41 ms ± 43.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
23.4 µs ± 937 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [48]:
tup_dim = (3, 4)
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
my_zeros_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [49]:
tup_dim = (3, 4)
my_ones_array = np.ones(tup_dim, dtype=np.int16)
my_ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [50]:
tup_dim = (3, 4)
my_seven_array = np.full(tup_dim,7, dtype=np.int16)
my_seven_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int16)

In [51]:
my_identity_array = np.identity(4, dtype=np.float64)
my_identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
my_rand_array = np.random.rand(3,4)
my_rand_array

array([[0.52782949, 0.84310943, 0.54098071, 0.45523216],
       [0.84799126, 0.36058489, 0.68520393, 0.73234928],
       [0.25682745, 0.2558643 , 0.62913864, 0.94715564]])

In [53]:
tup_dim = (3,4)
my_uninitialized_array = np.empty(tup_dim)
my_uninitialized_array

array([[0.52782949, 0.84310943, 0.54098071, 0.45523216],
       [0.84799126, 0.36058489, 0.68520393, 0.73234928],
       [0.25682745, 0.2558643 , 0.62913864, 0.94715564]])

In [54]:
my_range_array = np.arange(10,30,5)
my_range_array

array([10, 15, 20, 25])

In [55]:
my_spaced_array = np.linspace(0,5/3,6)
my_spaced_array

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [56]:
array_A = np.array([ [3,4,6], [0,8,1] ])
array_A

array([[3, 4, 6],
       [0, 8, 1]])

In [57]:
my_array =np.array( [ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])
my_array

array([[ 1,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 14, 16]])

In [58]:
my_array.ndim

2

In [59]:
my_array.shape

(3, 4)

In [60]:
my_array.size

12

In [61]:
my_array.dtype

dtype('int64')

In [69]:
import pandas as pd
import numpy as np
import os
HOUSING_PATH = '../ml/machine_learning/datasets/housing/'
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
my_df = housing_raw.iloc[ : 5]
print(my_df)
my_df.to_csv('housing_short.csv', index=False)

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [70]:
FILE = 'housing_short.csv'

In [71]:
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)
load_housing_data()

[array([-122.23, -122.22, -122.24, -122.25, -122.25]),
 array([37.88, 37.86, 37.85, 37.85, 37.85]),
 array([41., 21., 52., 52., 52.]),
 array([ 880., 7099., 1467., 1274., 1627.]),
 array([ 129., 1106.,  190.,  235.,  280.]),
 array([ 322., 2401.,  496.,  558.,  565.]),
 array([ 126., 1138.,  177.,  219.,  259.]),
 array([8.3252, 8.3014, 7.2574, 5.6431, 3.8462]),
 array([452600., 358500., 352100., 341300., 342200.]),
 array([b'NEAR BAY', b'NEAR BAY', b'NEAR BAY', b'NEAR BAY', b'NEAR BAY'],
       dtype='|S15')]

In [72]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [73]:
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [74]:
pwd

'/home/kunalpcea2433/cloudxlab_jupyter_notebooks'